// prisma/seed.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log(`Start seeding ...`);

  // 1. Define Example Users
  const users = [
    {
      name: 'Admin User',
      email: 'admin@example.com',
      // This MUST be a strong hash (e.g., generated by bcrypt)
      // Placeholder hash for 'password123'
      password: '$2b$10$2pWB5xXXPWHmeWv6aIU2eeonzFoXQSBhz/npwikIoJ7.etFBtiyGO', 
      //isVerified: true,
      emailVerified: new Date(),
    },
    {
      name: 'Test OAuth User',
      email: 'test@oauth.com',
      // OAuth users have no password hash
      password: null, 
      //sVerified: true,
      emailVerified: new Date(),
    },
  ];

  // 2. Insert Users into the Database
  for (const user of users) {
    const upsertedUser = await prisma.user.upsert({
      where: { email: user.email }, // Check if the user already exists
      update: {}, // Update fields if they exist (optional)
      create: user, // Create if they do not exist
    });
    console.log(`Created/Updated user with id: ${upsertedUser.id}`);
  }

  console.log(`Seeding finished.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });